- name: Download ZeroTier PGP key
  get_url:
    url: "{{ zerotier_pgp_url }}"
    dest: "{{ zerotier_apt_key_path }}"

- name: Import ZeroTier GPG key
  command: "gpg --no-default-keyring --keyring gnupg-ring:{{ zerotier_keyring_path }} --import {{ zerotier_apt_key_path }}"
  args:
    creates: "{{ zerotier_keyring_path }}"

- name: Set permissions for ZeroTier GPG key
  file:
    path: "{{ zerotier_keyring_path }}"
    mode: '0644'

- name: Check if Ubuntu release has dedicated repo
  uri:
    url: "{{ zerotier_download_base_url }}/debian/{{ zerotier_deb_release_repo }}"
  failed_when: false
  when:
    - ansible_facts['distribution'] == "Ubuntu"
  register: release_repo

- block:
  - name: Overwrite Ubuntu release repo name for cosmic
    set_fact:
      zerotier_deb_release_repo: bionic
    when: 
     - ansible_facts['distribution_major_version'] == "18"

  - name: Overwrite Ubuntu release repo name for focal
    set_fact:
      zerotier_deb_release_repo: bionic
    when: 
     - ansible_facts['distribution_major_version'] == "20"

  - name: Re-gather facts
    setup: ~

  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - release_repo.status == 404

- name: Add ZeroTier APT repository
  apt_repository:
    repo: "deb [signed-by={{ zerotier_keyring_path }}] {{ zerotier_download_base_url }}/debian/{{ zerotier_deb_release_repo }} {{ zerotier_deb_release_repo }} main"
    filename: zerotier
  register: zerotier_repo
