---
# Purpose: assert that the instance really ended up in the expected state.
# Molecule calls this playbook with `molecule verify`.
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Re-gather facts to load custom facts
      ansible.builtin.setup:
        filter: ansible_local

    - name: Verify ansible_local is properly accessible
      ansible.builtin.assert:
        that:
          - ansible_local is defined
          - ansible_local['zerotier'] is defined
          - ansible_local['zerotier']['node_id'] == "test-node-id-123"
        fail_msg: "ansible_local is not properly accessible"
        success_msg: "Successfully verified ansible_local access"

    - name: Verify the role didn't fail on ansible_local access
      ansible.builtin.debug:
        msg: "Role successfully handled ansible_local without errors"
